FROM alpine

RUN apk add --update --no-cache \
  bash \
  curl \
  git \
  python3 \
  py3-pip \
  sudo

RUN pip install --break-system-packages \
  numpy \
  pandas \
  pymysql \
  QuantLib-Python \
  scipy

RUN bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash'

RUN git clone https://github.com/sschlenkrich/OptionSmile

COPY ./run_script.sh /usr/local/bin/

CMD ["run_script.sh"]
